package osmium.pack;

import com.google.common.base.Splitter;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.Collection;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.imageio.ImageIO;
import org.bukkit.Material;
import osmium.math.Vec3;
import osmium.model.Bone;
import osmium.model.Cube;
import osmium.model.Face;
import osmium.model.ModelBlueprint;
import osmium.model.RenderPart;
import osmium.model.TextureAsset;
import osmium.util.Names;

public final class ResourcePackGenerator {
  private static final Gson GSON =
      new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

  private static final Pattern WHITESPACE_PATTERN = Pattern.compile("\\s+");
  private static final Splitter FRAME_ORDER_SPLITTER =
      Splitter.on(WHITESPACE_PATTERN).trimResults().omitEmptyStrings();
  private static final String ASSETS_DIRECTORY = "assets";
  private static final String DEFAULT_TEXTURE_KEY = "0";
  private static final String GENERATED_AT_FILE_NAME = "generated_at.txt";
  private static final String GENERATED_PACK_NAME = "pack.zip";
  private static final String ITEM_DIRECTORY = "item";
  private static final String ITEMS_DIRECTORY = "items";
  private static final String JSON_EXTENSION = ".json";
  private static final String MANIFEST_FILE_NAME = "modelengine_like_manifest.json";
  private static final String MINECRAFT_NAMESPACE = "minecraft";
  private static final String MODEL_CREDIT = "Generated by Osmium";
  private static final String MODELS_DIRECTORY = "models";
  private static final String PACK_DESCRIPTION = "Osmium generated pack";
  private static final String PACK_META_FILE_NAME = "pack.mcmeta";
  private static final String TEXTURES_DIRECTORY = "textures";
  private static final String UV_MODE = "modelengine_scaled_0_to_16_no_texture_size_signed_extents";
  private static final String ZIP_EXTENSION = ".zip";

  private static final String[] DISPLAY_CONTEXTS = {
    "fixed",
    "head",
    "thirdperson_righthand",
    "thirdperson_lefthand",
    "firstperson_righthand",
    "firstperson_lefthand",
    "ground",
    "gui"
  };

  private static final double DEFAULT_FLAT_SIZE = 0.35;
  private static final double EPSILON = 1.0E-6;
  private static final double MODEL_UNITS = 16.0;
  private static final int FALLBACK_CHECKER_SIZE = 4;
  private static final int FALLBACK_TEXTURE_SIZE = 16;
  private static final int HASH_PREFIX_LENGTH = 12;
  private static final int ROUNDING_SCALE = 1_000_000;
  private static final int RESOURCE_PACK_FORMAT_26_1 = 84;

  private final Logger logger;
  private final Path outputFolder;
  private final String namespace;
  private final int customModelDataStart;
  private final Material baseItem;

  public ResourcePackGenerator(
      Logger logger,
      Path outputFolder,
      String namespace,
      int customModelDataStart,
      Material baseItem) {
    this.logger = logger;
    this.outputFolder = outputFolder;
    this.namespace = namespace;
    this.customModelDataStart = customModelDataStart;
    this.baseItem = baseItem;
  }

  /** Generates the resource pack and returns the versioned zip path. */
  public Path generate(Collection<ModelBlueprint> models) throws IOException {
    Files.createDirectories(outputFolder);
    deleteGeneratedFiles();
    writePackMeta();

    int nextCustomModelData = customModelDataStart;
    Map<Integer, String> overrides = new TreeMap<>();
    for (ModelBlueprint model : models) {
      nextCustomModelData = writeModelParts(model, nextCustomModelData, overrides);
    }

    writeLegacyBaseItemModel(overrides);
    writeModernBaseItemDefinition(overrides);
    writeManifest(models);
    writeCacheBuster();

    Path zipPath = outputFolder.resolve(GENERATED_PACK_NAME);
    zip(zipPath);
    return copyVersionedZip(zipPath);
  }

  private static void deleteRecursively(Path path) throws IOException {
    if (!Files.exists(path)) {
      return;
    }

    try (Stream<Path> paths = Files.walk(path)) {
      for (Path currentPath : paths.sorted(Comparator.reverseOrder()).toList()) {
        Files.deleteIfExists(currentPath);
      }
    }
  }

  private static boolean needsAnimationMetadata(TextureAsset texture) {
    if (hasFrameOrder(texture)) {
      return true;
    }

    return texture.imageWidth() == texture.frameWidth()
        && texture.imageHeight() > texture.frameHeight()
        && texture.imageHeight() % texture.frameHeight() == 0;
  }

  private static boolean hasFrameOrder(TextureAsset texture) {
    return texture.frameOrder() != null && !texture.frameOrder().isBlank();
  }

  private static void writeFallbackTexture(Path outputPath) throws IOException {
    BufferedImage image =
        new BufferedImage(
            FALLBACK_TEXTURE_SIZE, FALLBACK_TEXTURE_SIZE, BufferedImage.TYPE_INT_ARGB);

    for (int y = 0; y < FALLBACK_TEXTURE_SIZE; y++) {
      for (int x = 0; x < FALLBACK_TEXTURE_SIZE; x++) {
        boolean useMagenta = ((x / FALLBACK_CHECKER_SIZE + y / FALLBACK_CHECKER_SIZE) & 1) == 0;
        image.setRGB(x, y, (useMagenta ? Color.MAGENTA : Color.BLACK).getRGB());
      }
    }

    ImageIO.write(image, "png", outputPath.toFile());
  }

  private static JsonArray cubeFrom(Cube cube) {
    Vec3 size = displaySize(cube);
    double inflation = cube.inflate();

    return numbers(
        8 - size.x() / 2 - inflation, 8 - size.y() / 2 - inflation, 8 - size.z() / 2 - inflation);
  }

  private static JsonArray cubeTo(Cube cube) {
    Vec3 size = displaySize(cube);
    double inflation = cube.inflate();

    return numbers(
        8 + size.x() / 2 + inflation, 8 + size.y() / 2 + inflation, 8 + size.z() / 2 + inflation);
  }

  private static Vec3 displaySize(Cube cube) {
    Vec3 size = cube.signedSize();
    return new Vec3(expandFlat(size.x()), expandFlat(size.y()), expandFlat(size.z()));
  }

  private static double expandFlat(double value) {
    return Math.abs(value) < EPSILON ? DEFAULT_FLAT_SIZE : value;
  }

  private static double convertUv(double value, int textureSize) {
    return value / Math.max(textureSize, 1) * MODEL_UNITS;
  }

  private static IdentityHashMap<TextureAsset, String> numericTextureKeys(ModelBlueprint model) {
    IdentityHashMap<TextureAsset, String> textureKeys = new IdentityHashMap<>();

    for (Map.Entry<String, TextureAsset> entry : model.textures().entrySet()) {
      if (isNumericTextureKey(entry.getKey()) && !textureKeys.containsKey(entry.getValue())) {
        textureKeys.put(entry.getValue(), entry.getKey());
      }
    }

    return textureKeys;
  }

  private static boolean isNumericTextureKey(String value) {
    if (value.isEmpty()) {
      return false;
    }

    for (int i = 0; i < value.length(); i++) {
      char character = value.charAt(i);
      if (character < '0' || character > '9') {
        return false;
      }
    }

    return true;
  }

  private static String textureReferenceKey(
      TextureAsset texture, IdentityHashMap<TextureAsset, String> numericTextureKeys) {
    return numericTextureKeys.getOrDefault(texture, DEFAULT_TEXTURE_KEY);
  }

  private static JsonObject display() {
    JsonObject display = new JsonObject();

    for (String context : DISPLAY_CONTEXTS) {
      JsonObject transform = new JsonObject();
      transform.add("rotation", numbers(0, 0, 0));
      transform.add("translation", numbers(0, 0, 0));
      transform.add("scale", numbers(1, 1, 1));
      display.add(context, transform);
    }

    return display;
  }

  private static JsonArray numbers(double... values) {
    JsonArray array = new JsonArray();

    for (double value : values) {
      array.add(Math.rint(value * ROUNDING_SCALE) / ROUNDING_SCALE);
    }

    return array;
  }

  private static String pathAfterNamespace(String namespacedPath) {
    return namespacedPath.substring(namespacedPath.indexOf(':') + 1);
  }

  private static String partName(Bone bone, Cube cube, int partIndex) {
    return Names.key(bone.name() + "_" + cube.name() + "_" + partIndex);
  }

  private static String baseItemKey(Material baseItem) {
    return Names.key(baseItem.name());
  }

  private static boolean isVersionedPackZip(Path path) {
    String fileName = path.getFileName().toString();
    return fileName.startsWith("pack-") && fileName.endsWith(ZIP_EXTENSION);
  }

  private static boolean isZipFile(Path path) {
    return path.getFileName().toString().endsWith(ZIP_EXTENSION);
  }

  private static JsonObject modelReference(String modelPath) {
    JsonObject model = new JsonObject();
    model.addProperty("type", "minecraft:model");
    model.addProperty("model", modelPath);
    return model;
  }

  private static JsonObject packRoot() {
    JsonObject pack = new JsonObject();
    pack.addProperty("description", PACK_DESCRIPTION);
    pack.addProperty("min_format", RESOURCE_PACK_FORMAT_26_1);
    pack.addProperty("max_format", RESOURCE_PACK_FORMAT_26_1);

    JsonObject root = new JsonObject();
    root.add("pack", pack);
    return root;
  }

  private static Path mcmetaPath(Path pngPath) {
    return Path.of(pngPath + ".mcmeta");
  }

  private static void writeJson(Path outputPath, JsonObject json) throws IOException {
    createParentDirectories(outputPath);
    Files.writeString(outputPath, GSON.toJson(json), StandardCharsets.UTF_8);
  }

  private static void createParentDirectories(Path path) throws IOException {
    Path parent = path.getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }
  }

  private int writeModelParts(
      ModelBlueprint model, int nextCustomModelData, Map<Integer, String> overrides)
      throws IOException {
    model.clearParts();
    writeTextures(model);

    IdentityHashMap<TextureAsset, String> textureKeys = numericTextureKeys(model);
    int customModelData = nextCustomModelData;

    for (Bone bone : model.bones()) {
      if (!bone.visible()) {
        continue;
      }

      int partIndex = 0;
      for (String cubeId : bone.cubeIds()) {
        Optional<Cube> cube = model.cube(cubeId);
        if (cube.isEmpty()) {
          continue;
        }

        String partName = partName(bone, cube.get(), partIndex);
        String modelPath = namespacedModelPath(model, partName);
        String itemKey = namespacedItemKey(model, partName);
        RenderPart renderPart =
            new RenderPart(partName, itemKey, modelPath, customModelData, bone, cube.get());

        partIndex++;
        model.addPart(renderPart);
        writeCubeModel(model, renderPart, textureKeys);
        writeItemDefinition(itemKey, modelPath);
        overrides.put(customModelData, modelPath);
        customModelData++;
      }
    }

    return customModelData;
  }

  private String namespacedModelPath(ModelBlueprint model, String partName) {
    return namespace + ":item/" + model.id() + "/" + partName;
  }

  private String namespacedItemKey(ModelBlueprint model, String partName) {
    return namespace + ':' + model.id() + '/' + partName;
  }

  private Path namespaceAssetPath(String assetType, String relativePath) {
    return outputFolder
        .resolve(ASSETS_DIRECTORY)
        .resolve(namespace)
        .resolve(assetType)
        .resolve(relativePath);
  }

  private Path namespaceJsonAssetPath(String assetType, String namespacedPath) {
    return namespaceAssetPath(assetType, pathAfterNamespace(namespacedPath) + JSON_EXTENSION);
  }

  private Path minecraftModelPath(String item) {
    return outputFolder
        .resolve(ASSETS_DIRECTORY)
        .resolve(MINECRAFT_NAMESPACE)
        .resolve(MODELS_DIRECTORY)
        .resolve(ITEM_DIRECTORY)
        .resolve(item + JSON_EXTENSION);
  }

  private Path minecraftItemPath(String item) {
    return outputFolder
        .resolve(ASSETS_DIRECTORY)
        .resolve(MINECRAFT_NAMESPACE)
        .resolve(ITEMS_DIRECTORY)
        .resolve(item + JSON_EXTENSION);
  }

  private void deleteGeneratedFiles() throws IOException {
    deleteRecursively(outputFolder.resolve(ASSETS_DIRECTORY).resolve(namespace));

    String item = baseItemKey(baseItem);
    Files.deleteIfExists(minecraftModelPath(item));
    Files.deleteIfExists(minecraftItemPath(item));
    Files.deleteIfExists(outputFolder.resolve(GENERATED_PACK_NAME));
    Files.deleteIfExists(outputFolder.resolve(GENERATED_AT_FILE_NAME));
    Files.deleteIfExists(outputFolder.resolve(MANIFEST_FILE_NAME));

    if (!Files.isDirectory(outputFolder)) {
      return;
    }

    try (Stream<Path> paths = Files.list(outputFolder)) {
      for (Path path :
          paths
              .filter(Files::isRegularFile)
              .filter(ResourcePackGenerator::isVersionedPackZip)
              .toList()) {
        Files.deleteIfExists(path);
      }
    }
  }

  private void writePackMeta() throws IOException {
    writeJson(outputFolder.resolve(PACK_META_FILE_NAME), packRoot());
  }

  private void writeTextures(ModelBlueprint model) throws IOException {
    for (TextureAsset texture : uniqueTexturesByModelPath(model).values()) {
      writeTexture(model, texture);
    }
  }

  private Map<String, TextureAsset> uniqueTexturesByModelPath(ModelBlueprint model) {
    Map<String, TextureAsset> textures = new LinkedHashMap<>();

    for (TextureAsset texture : model.textures().values()) {
      textures.put(texture.modelPath(), texture);
    }

    return textures;
  }

  private void writeTexture(ModelBlueprint model, TextureAsset texture) throws IOException {
    Path outputPath = textureOutputPath(texture);
    createParentDirectories(outputPath);

    Optional<byte[]> embeddedBytes = texture.embeddedBytesOptional();
    if (embeddedBytes.isPresent()) {
      Files.write(outputPath, embeddedBytes.get());
      writeMcmeta(outputPath, texture);
      return;
    }

    Optional<Path> sourcePath = texture.sourcePathOptional();
    if (sourcePath.isPresent() && Files.isRegularFile(sourcePath.get())) {
      Files.copy(sourcePath.get(), outputPath, StandardCopyOption.REPLACE_EXISTING);
      writeMcmeta(outputPath, texture);
      return;
    }

    writeFallbackTexture(outputPath);
    logger.warning("Missing texture " + texture.name() + " for " + model.id());
  }

  private Path textureOutputPath(TextureAsset texture) {
    return namespaceAssetPath(TEXTURES_DIRECTORY, pathAfterNamespace(texture.modelPath()) + ".png");
  }

  private void writeMcmeta(Path pngPath, TextureAsset texture) throws IOException {
    if (!needsAnimationMetadata(texture)) {
      return;
    }

    JsonObject root = new JsonObject();
    root.add("animation", animationMetadata(texture));
    writeJson(mcmetaPath(pngPath), root);
  }

  private JsonObject animationMetadata(TextureAsset texture) {
    JsonObject animation = new JsonObject();
    animation.addProperty("frametime", Math.max(texture.frameTime(), 1));

    if (texture.frameInterpolate()) {
      animation.addProperty("interpolate", true);
    }

    if (hasFrameOrder(texture)) {
      JsonArray frames = frameOrder(texture);
      if (!frames.isEmpty()) {
        animation.add("frames", frames);
      }
    }

    return animation;
  }

  private JsonArray frameOrder(TextureAsset texture) {
    JsonArray frames = new JsonArray();

    for (String frame : FRAME_ORDER_SPLITTER.split(texture.frameOrder().trim())) {
      try {
        frames.add(Integer.parseInt(frame));
      } catch (NumberFormatException exception) {
        logger.log(
            Level.WARNING,
            "Ignoring invalid animation frame '" + frame + "' for texture " + texture.name(),
            exception);
      }
    }

    return frames;
  }

  private void writeCubeModel(
      ModelBlueprint model,
      RenderPart renderPart,
      IdentityHashMap<TextureAsset, String> textureKeys)
      throws IOException {
    JsonObject root = new JsonObject();
    root.addProperty("credit", MODEL_CREDIT);
    root.addProperty("ambientocclusion", false);
    root.add("textures", textures(model));
    root.add("elements", elements(renderPart.cube(), model, textureKeys));
    root.add("display", display());

    writeJson(namespaceJsonAssetPath(MODELS_DIRECTORY, renderPart.modelPath()), root);
  }

  private JsonObject textures(ModelBlueprint model) {
    TextureAsset primaryTexture = model.texture(DEFAULT_TEXTURE_KEY);
    JsonObject textures = new JsonObject();

    for (Map.Entry<String, TextureAsset> entry : model.textures().entrySet()) {
      if (isNumericTextureKey(entry.getKey())) {
        textures.addProperty(entry.getKey(), entry.getValue().modelPath());
      }
    }

    if (!textures.has(DEFAULT_TEXTURE_KEY)) {
      textures.addProperty(DEFAULT_TEXTURE_KEY, primaryTexture.modelPath());
    }

    textures.addProperty("particle", "#" + DEFAULT_TEXTURE_KEY);
    return textures;
  }

  private JsonArray elements(
      Cube cube, ModelBlueprint model, IdentityHashMap<TextureAsset, String> textureKeys) {
    JsonArray elements = new JsonArray();
    elements.add(element(cube, model, textureKeys));
    return elements;
  }

  private JsonObject element(
      Cube cube, ModelBlueprint model, IdentityHashMap<TextureAsset, String> textureKeys) {
    JsonObject element = new JsonObject();
    element.addProperty("name", cube.name());
    element.add("from", cubeFrom(cube));
    element.add("to", cubeTo(cube));
    element.add("faces", faces(cube, model, textureKeys));
    return element;
  }

  private JsonObject faces(
      Cube cube, ModelBlueprint model, IdentityHashMap<TextureAsset, String> textureKeys) {
    JsonObject faces = new JsonObject();

    for (Face face : cube.faces().values()) {
      faces.add(face.direction(), face(face, model, textureKeys));
    }

    return faces;
  }

  private JsonObject face(
      Face face, ModelBlueprint model, IdentityHashMap<TextureAsset, String> textureKeys) {
    TextureAsset texture = model.texture(face.textureKey());
    JsonObject faceJson = new JsonObject();
    faceJson.add(
        "uv",
        numbers(
            convertUv(face.u1(), texture.frameWidth()),
            convertUv(face.v1(), texture.frameHeight()),
            convertUv(face.u2(), texture.frameWidth()),
            convertUv(face.v2(), texture.frameHeight())));
    faceJson.addProperty("texture", "#" + textureReferenceKey(texture, textureKeys));

    if (face.rotation() != 0) {
      faceJson.addProperty("rotation", face.rotation());
    }

    return faceJson;
  }

  private void writeItemDefinition(String itemKey, String modelPath) throws IOException {
    JsonObject root = new JsonObject();
    root.add("model", modelReference(modelPath));
    writeJson(namespaceJsonAssetPath(ITEMS_DIRECTORY, itemKey), root);
  }

  private void writeLegacyBaseItemModel(Map<Integer, String> overrides) throws IOException {
    String item = baseItemKey(baseItem);

    JsonObject root = new JsonObject();
    root.addProperty("parent", "minecraft:item/generated");
    root.add("textures", legacyBaseTextures(item));
    root.add("overrides", legacyOverrides(overrides));

    writeJson(minecraftModelPath(item), root);
  }

  private JsonObject legacyBaseTextures(String item) {
    JsonObject textures = new JsonObject();
    textures.addProperty("layer0", "minecraft:item/" + item);
    return textures;
  }

  private JsonArray legacyOverrides(Map<Integer, String> overrides) {
    JsonArray legacyOverrides = new JsonArray();

    for (Map.Entry<Integer, String> entry : overrides.entrySet()) {
      JsonObject predicate = new JsonObject();
      predicate.addProperty("custom_model_data", entry.getKey());

      JsonObject override = new JsonObject();
      override.add("predicate", predicate);
      override.addProperty("model", entry.getValue());
      legacyOverrides.add(override);
    }

    return legacyOverrides;
  }

  private void writeModernBaseItemDefinition(Map<Integer, String> overrides) throws IOException {
    String item = baseItemKey(baseItem);

    JsonObject root = new JsonObject();
    root.add("model", rangeDispatchModel(item, overrides));
    writeJson(minecraftItemPath(item), root);
  }

  private JsonObject rangeDispatchModel(String item, Map<Integer, String> overrides) {
    JsonObject rangeDispatch = new JsonObject();
    rangeDispatch.addProperty("type", "minecraft:range_dispatch");
    rangeDispatch.addProperty("property", "minecraft:custom_model_data");
    rangeDispatch.addProperty("index", 0);
    rangeDispatch.addProperty("scale", 1.0);
    rangeDispatch.add("entries", rangeDispatchEntries(overrides));
    rangeDispatch.add("fallback", modelReference("minecraft:item/" + item));
    return rangeDispatch;
  }

  private JsonArray rangeDispatchEntries(Map<Integer, String> overrides) {
    JsonArray entries = new JsonArray();

    for (Map.Entry<Integer, String> entry : overrides.entrySet()) {
      JsonObject row = new JsonObject();
      row.addProperty("threshold", entry.getKey().floatValue());
      row.add("model", modelReference(entry.getValue()));
      entries.add(row);
    }

    return entries;
  }

  private void writeManifest(Collection<ModelBlueprint> models) throws IOException {
    JsonObject root = new JsonObject();
    root.addProperty("generated_at", Instant.now().toString());
    root.addProperty("uv_mode", UV_MODE);
    root.add("models", manifestModels(models));

    writeJson(outputFolder.resolve(MANIFEST_FILE_NAME), root);
  }

  private JsonArray manifestModels(Collection<ModelBlueprint> models) {
    JsonArray manifestModels = new JsonArray();

    for (ModelBlueprint model : models) {
      manifestModels.add(manifestModel(model));
    }

    return manifestModels;
  }

  private JsonObject manifestModel(ModelBlueprint model) {
    JsonObject manifestModel = new JsonObject();
    manifestModel.addProperty("id", model.id());
    manifestModel.addProperty("source", model.source().getFileName().toString());
    manifestModel.add("faces", manifestFaces(model));
    return manifestModel;
  }

  private JsonArray manifestFaces(ModelBlueprint model) {
    JsonArray faces = new JsonArray();
    IdentityHashMap<TextureAsset, String> textureKeys = numericTextureKeys(model);

    for (Cube cube : model.cubes().values()) {
      for (Face face : cube.faces().values()) {
        faces.add(manifestFace(model, cube, face, textureKeys));
      }
    }

    return faces;
  }

  private JsonObject manifestFace(
      ModelBlueprint model,
      Cube cube,
      Face face,
      IdentityHashMap<TextureAsset, String> textureKeys) {
    TextureAsset texture = model.texture(face.textureKey());

    JsonObject faceJson = new JsonObject();
    faceJson.addProperty("cube", cube.name());
    faceJson.addProperty("reversed", cube.reversed());
    faceJson.add("cube_from", numbers(cube.from().x(), cube.from().y(), cube.from().z()));
    faceJson.add("cube_to", numbers(cube.to().x(), cube.to().y(), cube.to().z()));
    faceJson.addProperty("dir", face.direction());
    faceJson.addProperty("texture", textureReferenceKey(texture, textureKeys));
    faceJson.add("raw_uv", numbers(face.u1(), face.v1(), face.u2(), face.v2()));
    faceJson.add(
        "written_uv",
        numbers(
            convertUv(face.u1(), texture.frameWidth()),
            convertUv(face.v1(), texture.frameHeight()),
            convertUv(face.u2(), texture.frameWidth()),
            convertUv(face.v2(), texture.frameHeight())));

    return faceJson;
  }

  private void writeCacheBuster() throws IOException {
    String generatedAt = "Generated " + Instant.now() + System.lineSeparator();
    Files.writeString(
        outputFolder.resolve(GENERATED_AT_FILE_NAME), generatedAt, StandardCharsets.UTF_8);
  }

  private void zip(Path zipPath) throws IOException {
    try (ZipOutputStream zipOutputStream = new ZipOutputStream(Files.newOutputStream(zipPath));
        Stream<Path> paths = Files.walk(outputFolder)) {
      for (Path path : paths.filter(Files::isRegularFile).sorted().toList()) {
        if (path.equals(zipPath) || isZipFile(path)) {
          continue;
        }

        zipOutputStream.putNextEntry(new ZipEntry(zipEntryName(path)));
        Files.copy(path, zipOutputStream);
        zipOutputStream.closeEntry();
      }
    }
  }

  private String zipEntryName(Path path) {
    return outputFolder.relativize(path).toString().replace('\\', '/');
  }

  private Path copyVersionedZip(Path zipPath) throws IOException {
    byte[] bytes = Files.readAllBytes(zipPath);
    String hash = sha1Prefix(bytes);

    Path versionedZip = outputFolder.resolve("pack-" + hash + ZIP_EXTENSION);
    Files.copy(zipPath, versionedZip, StandardCopyOption.REPLACE_EXISTING);
    return versionedZip;
  }

  private String sha1Prefix(byte[] bytes) throws IOException {
    try {
      byte[] digest = MessageDigest.getInstance("SHA-1").digest(bytes);
      return HexFormat.of().formatHex(digest).substring(0, HASH_PREFIX_LENGTH);
    } catch (NoSuchAlgorithmException exception) {
      throw new IOException("SHA-1 digest algorithm is unavailable.", exception);
    }
  }
}
